default_platform(:android)

platform :android do

  desc "Deploy Kotlin Android App to Production"
  lane :production do

    # Build AAB with Gradle
    gradle(
      task: "bundle",
      build_type: "Release",
      flags: "--stacktrace"
    )

    # Upload to Play Store
    upload_to_play_store(
      track: "production",
      aab: lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH],
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )

  end
end