default_platform(:android)

platform :android do

  desc "Deploy Kotlin Android App to Production"
  lane :production do

    # Build AAB with Gradle
    gradle(
      task: "bundle",
      build_type: "Release"
    )

    # Upload to Play Store
    upload_to_play_store(
      track: "production",
      aab: "../app/build/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )

  end
end