name: Deploy to Production

on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+*" # Trigger on version tags

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: "3.2"
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  flutter-version: "3.19.6"
            - name: Install Flutter dependencies
              run: flutter pub get
            - name: Install Bundler & Fastlane
              working-directory: android
              run: |
                  gem install bundler
                  bundle install
            - name: Decode service account key
              run: |
                  mkdir -p android/fastlane/keys
                  echo "${{ secrets.GOOGLE_PLAY_JSON }}" | base64 --decode > android/fastlane/keys/play-store-service-account.json
            - name: Deploy to Production
              working-directory: android
              run: bundle exec fastlane production
